services:
  db:
    image: postgres
    restart: always
    container_name: db
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - app

  bot:
    build:
      context: .
    container_name: tg_bot
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - temp:/temp
      - .:/app
    networks:
      - app


volumes:
  postgresdb:
  temp:

networks:
  app: