"""run_database

Revision ID: 467ef24ce7a4
Revises: 
Create Date: 2024-11-27 13:38:04.190522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '467ef24ce7a4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('user_number', sa.String(), nullable=False),
    sa.Column('telegram_user', sa.String(), nullable=False),
    sa.Column('need_pay_date', sa.DateTime(), nullable=False),
    sa.Column('pay_date', sa.DateTime(), nullable=False),
    sa.Column('activated_date', sa.DateTime(), nullable=False),
    sa.Column('stay_on_pause', sa.Boolean(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('pay_lists', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
