"""finish 1.2

Revision ID: ad3bfcb04e9d
Revises: 1343561f3332
Create Date: 2024-12-23 19:23:30.583824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad3bfcb04e9d'
down_revision: Union[str, None] = '1343561f3332'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'need_pay_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('users', 'invoice_day',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('users', 'activated_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'activated_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('users', 'invoice_day',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('users', 'need_pay_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
